### ISSUE TITLE
Error: Analyse_Manta_Overlap.R

### ISSUE THREAD

**Issue by rboxtel** [jdeligt/Genetics#6]
If I run this tool, I'm getting an error:

In valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE) :
  GRanges object contains 1 out-of-bound range located on sequence MT.
  Note that only ranges located on a non-circular sequence whose length
  is not NA can be considered out-of-bound (use seqlengths() and
  isCircular() to get the lengths and circularity flags of the underlying
  sequences). You can use trim() to trim these ranges. See
  ?`trim,GenomicRanges-method` for more information.

There seems to be a problem with the MT DNA?

**Comment by jdeligt** [comment]
seems like you're using a non circular version of MT in R or the pipeline, thereby causing out of bound issues.
